language: cpp
sudo: required
dist: xenial

os:
  - linux

compiler:
  - clang
#  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - freeglut3-dev
      - libpulse-dev
      - libflac-dev
      - libflac++-dev
      - zlib1g-dev
      - libssl-dev

before_install:
  - if [ "$CC" = "clang" ]; then
      export CXX="clang++" CC="clang";
    fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$CXX" = "g++" ]; then
      export CXX="g++" CC="gcc";
      export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01';
    fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo add-apt-repository ppa:beineri/opt-qt-5.11.3-xenial -y;
      sudo apt-get update;
      sudo apt-get install qt511base qt511tools qt511declarative qt511quickcontrols2 qt511svg -y --allow-unauthenticated;
    fi;

before_script:
  - source /opt/qt511/bin/qt511-env.sh
  - cmake --version
  - mkdir build && cd build
  - cmake .. -Wdev -DCMAKE_CXX_COMPILER=$(which $CXX) -DCMAKE_C_COMPILER=$(which $CC) -DCMAKE_INSTALL_PREFIX=$HOME

script:
  - cmake --build . --target install
  - cmake --build . --target uninstall
